---
- name: Install and configure Nginx
  hosts: web
  become: true

  tasks:
    - name: Update APT packages
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Deploy custom index.html file
      copy:
        src: /home/ubuntu/Ansible_Nginx_AWS/site/index.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'
